'use client'

import React from 'react'

/**
 * AIReport component - Displays the AI-generated cleaning analysis report.
 * Formats the markdown report for nice presentation.
 */
export default function AIReport({ report }) {
  // Simple markdown to React elements conversion
  const renderReport = (text) => {
    const lines = text.split('\n')
    const elements = []
    let listItems = []

    lines.forEach((line, index) => {
      // Headers
      if (line.startsWith('## ')) {
        if (listItems.length > 0) {
          elements.push(
            <ul key={`list-${index}`} className="list-disc list-inside mb-4 space-y-1">
              {listItems.map((item, i) => (
                <li key={i} className="text-gray-700">
                  {item}
                </li>
              ))}
            </ul>
          )
          listItems = []
        }

        elements.push(
          <h2 key={index} className="text-2xl font-bold text-gray-900 mt-6 mb-3">
            {line.replace('## ', '')}
          </h2>
        )
      }
      // Subheaders
      else if (line.startsWith('### ')) {
        elements.push(
          <h3 key={index} className="text-xl font-semibold text-gray-800 mt-4 mb-2">
            {line.replace('### ', '')}
          </h3>
        )
      }
      // List items
      else if (line.startsWith('- ')) {
        listItems.push(line.replace('- ', ''))
      }
      // Bold text
      else if (line.trim() && !line.startsWith('#')) {
        if (listItems.length > 0) {
          elements.push(
            <ul key={`list-${index}`} className="list-disc list-inside mb-4 space-y-1">
              {listItems.map((item, i) => (
                <li key={i} className="text-gray-700">
                  {item}
                </li>
              ))}
            </ul>
          )
          listItems = []
        }

        // Parse inline bold
        const parts = line.split(/\*\*(.*?)\*\*/g)
        const element = (
          <p key={index} className="text-gray-700 mb-4 leading-relaxed">
            {parts.map((part, i) =>
              i % 2 === 1 ? (
                <strong key={i}>{part}</strong>
              ) : (
                <span key={i}>{part}</span>
              )
            )}
          </p>
        )
        elements.push(element)
      }
    })

    // Add remaining list items
    if (listItems.length > 0) {
      elements.push(
        <ul key="final-list" className="list-disc list-inside mb-4 space-y-1">
          {listItems.map((item, i) => (
            <li key={i} className="text-gray-700">
              {item}
            </li>
          ))}
        </ul>
      )
    }

    return elements
  }

  return (
    <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-lg p-8 border border-indigo-200">
      <div className="prose prose-sm max-w-none text-gray-800">
        {renderReport(report)}
      </div>

      <div className="mt-8 p-4 bg-indigo-100 rounded-lg border border-indigo-300">
        <p className="text-sm text-indigo-900">
          💡 <strong>Tip:</strong> This report was generated by AI based on the
          cleaning operations performed. Review it carefully and apply any
          recommendations as needed for your specific use case.
        </p>
      </div>
    </div>
  )
}
